articles/urls.py
from django.urls import path
from . import views

app_name = 'articles' # url name space 를 만든 것 
# ==> url 들이 articles 에 있는 ___ 페이지가 된다 (/articles/_______)
urlpatterns = [
    path('', views.index, name='index'),
    # 데이터를 전달받아서 article 생성
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    # 댓글 예: /article/3/comments/
    path('<int:article_pk>/comments/', views.comment_create, name='comment_create'),
    # comment의 pk 를 variable routing 으로 받을 것 (댓글 데이터에도 다 pk 값 달려 있음)

    # 댓글 삭제하기(190924) url 추가
    # /articles/3/comments/2/delete 형식으로 만들 것 
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('jobs/', include('jobs.urls')),
    path('admin/', admin.site.urls),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs' # url name space 를 만든 것 
# ==> url 들이 jobs 에 있는 ___ 페이지가 된다
urlpatterns = [
    path('', views.index, name='index'),
    path('past_job/', views.past_job, name='past_job'),
]

articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='comments')
    # 1. Article model class 를 명시해준다.(1:N 관계를 만들 때 반드시 1이 먼저 선언)
    # 2. on_delete=models.CASCADE : Article이 삭제되면 Comment 도 함께 삭제되도록
    # primary key 값만 남음 article_id 와 article(Model에 정의한 대로)을 같은 작업으로 받아들임
    # 3. related_name : Article instance 가 comment를 역참조하는 이름 정의
    content = models.CharField(max_length=200)
    # 데이터가 새로 추가됐을 때만 현재 시간 자동으로 생성됨
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)  # 추가나 수정이나 언제든지 시간 기록

    # 클래스 안에 또 클래스 (Django meta option 검색해보기)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.content

jobs/models.py
from django.db import models

# Create your models here.
class Job(models.Model):
    name = models.CharField(max_length=20)
    past_job = models.TextField()

    # Job 의 데이터가 어떻게 정의되는지 알려주는 함수
    def __str__(self):
        return self.name

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment


def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


# POST /articles/create/
def create(request):
    # 만약 POST 요청으로 들어오면 사용자 데이터 받아서 article 생성
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        article = Article()
        article.title = title
        article.content = content
        article.save()
        # 방금 만든 article 의 상세보기 페이지로 보냄
        return redirect('articles:detail', article.pk)
    # GET 요청이면 생성 form 보여줄 것
    else:
        return render(request, 'articles/create.html')


def detail(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)

    # 현재 article 에 달린 모든 댓글 다 꺼내기
    # comments = article.comment_set.all()
    # related_names='comments' 이므로
    comments = article.comments.all()

    # 저장해서 context에 넣어서 넘김
    context = {
        'article': article,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


# 사용자로부터 받은 article_pk 값에 해당하는 article 을 삭제한다.
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    # 보안문제: 들어온 요청이 POST 일 때만 삭제해
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')  # 글 목록으로 re-direct
    else:
        return redirect('articles:detail', article_pk)  # 삭제 불가능
        # 삭제되지 않은 채 삭제버튼이 존재하는 상세보기 페이지를 그대로 보여줌


# /articles/5/update/ 로 들어옴
def update(request, article_pk):
    # 어떤 메소드가 들어왔는지 안쪽에서 확인
    article = get_object_or_404(Article, pk=article_pk)
    # POST : 실제 Update 로직 수행
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        # 수정 후 save()
        article.title = title
        article.content = content
        article.save()
        return redirect('articles:detail', article.pk)

    else:
        context = {'article': article}
        return render(request, 'articles/update.html', context)


# 댓글 다는 함수 / variable routing 있으면 request 말고 다른 변수 받는다.
def comment_create(request, article_pk):

    # article_pk 에 해당하는 article 에 새로운 comment 생성
    # 생성한 다음 article detail page 로 redirect
    article = get_object_or_404(Article, pk=article_pk)
    # 몇번 아티클에 달아줄지 정하는 것

    if request.method == 'POST':
        content = request.POST.get('content')
        comment = Comment()
        comment.content = content
        comment.article = article
        comment.save()
    return redirect('articles:detail', article.pk)


# 첫번째 인자는 무조건 request, 다음 인자는 url에서 var routing으로 넘어오는 인자 순서대로 받는다.
def comment_delete(request, article_pk, comment_pk):
    # post 요청으로 들어왔다면 그 때만 댓삭!
    if request.method == 'POST':
        # comment_pk 해당 댓글 삭제
        # 어떤 모델에서 가져올지 받고, primary key 받아서 꺼내준다. (없으면 404 넘긴다.)
        comment = get_object_or_404(Comment, pk=comment_pk)
        # comment가 있으면 삭제
        comment.delete()

    # 댓삭 후 detail 페이지로 이동시킴
    # 어떤 페이지로 넘길지에 대한 article pk 가 필요하다. (마침 위에서 var routing으로 받았으므로 _ )
    return redirect('articles:detail', article_pk)

jobs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Job

# random 과 비슷한 역할 
from faker import Faker

# Create your views here.
def index(request):
    return render(request, 'jobs/index.html')


def past_job(request):
    # 만약 POST 요청으로 들어오면 사용자 데이터 받아서 article 생성
    fake = Faker('ko_kr')
    name = request.POST.get('name')
    if Job.objects.filter(name=name):
        job = Job.objects.get(name=name)
    else: 
        job = Job()
        job.name = name
        job.past_job = fake.job()
        job.save()
    context = {'job':job}
    return render(request, 'jobs/past_job.html', context)

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block body %}

<h1>Create New Article</h1>
{% comment %} method 안 적으면 GET으로 인식 --> POST로 적어야 POST 요청 {% endcomment %}
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <input type="text" name='title'><br>
  <textarea name="content" cols="30" rows="10"></textarea>
  <button type="submit">CREATE</button>
<br/>
</form>

<a href="{% url 'articles:index' %}">Back To INDEX Page</a>

{% endblock body %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock title %}

{% block body %}

  <h1>{{ article.title }}</h1>
  <p>작성일자 : {{ article.created_at }}</p>
  <hr>
  <p>{{ article.content }}</p>
  <hr>

  <a href="{% url 'articles:index' %}">[뒤로가기]</a>

  {% comment %} 현재 담긴 detail 을 유치한 채 update 로 GET 요청 {% endcomment %}
  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>

  {% comment %} article.pk 를 variable routing 으로 넘겨준다. {% endcomment %}
  <form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('Are you sure?')">
    {% csrf_token %}
    <button type="submit">[삭제하기]</button>
  </form>

  <h4>Comments</h4>
  {% comment %} Comment 입력 위한 Form {% endcomment %}
  <form action="{% url 'articles:comment_create' article.pk %}" method='POST'>
    {% csrf_token %}
    {% comment %} 나중에 넣는 데이터를 content 라는 이름으로 받아서 사용하려고 함  {% endcomment %}
    <input type="text" name="content">
    <button type="submit">댓글작성</button> 
  </form>


  {% comment %} 데이터가 여러개 -> 반복문(for) 돌면서 꺼내서 하나하나 표시해주기 {% endcomment %}
  <ul>
    {% for comment in comments %}
      <li>{{ comment.content }}
        <!-- form tag 로 댓글 하나하나마다 삭제버튼 같이 만들어준다.-->
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <button type="submit">댓글 삭제하기</button>
        </form>
      </li>
    {% empty %}
      <p>아직 댓글이 없습니다.</p>
    {% endfor %}
  </ul>

{% endblock body %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %}Articles::Index{% endblock title %}

{% block body %}

  <h1>Articles</h1>
  <a href="{% url 'articles:create' %}">CREATE</a><hr> 
  {% for article in articles %}
    <div>
      <h3>{{ article.pk}}. <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></h3>
      <p>{{ article.content }}</p>
    </div>
  {% endfor %}
  
{% endblock body %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %}Update Article{% endblock title %}

{% comment %} create.html 에서 붙여넣고 update 로 수정 {% endcomment %}
{% block body %}

<h1>Update Article</h1>
{% comment %} method 안 적으면 GET으로 인식 --> POST로 적어야 POST 요청 {% endcomment %}
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  {% comment %} 원래 값이 채워져 있어야 하므로 value 옵션 준다.  {% endcomment %}
  <input type="text" name='title' value="{{ article.title }}"><br>
  <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea>
  <button type="submit">UPDATE</button>
<br/>
</form>

{% endblock body %}

crud/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  {% block body %}
  {% endblock body %}
</body>
</html>

jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block title %}이름 입력 페이지{% endblock title %}

{% block body %}

{% comment %} - `name` 을 입력할 수 있는 `form` 이 있으며 `form` 의 method 는 `POST` 입니다. `form` 은 `/jobs/past_job/` 으로 제출됩니다. {% endcomment %}

<form action="{% url 'jobs:past_job' %}" method='POST'>
  {% csrf_token %}
  <input type="text" name='name'>
  <button type="submit">입력하기</button>
</form>

{% endblock body %}

jobs/templates/jobs/past_job.html
{% extends 'base.html' %}

{% block title %}Past_Job{% endblock title %}

{% block body %}

  <h1>{{ job.name }}아 {{ job.past_job }}가 되기 위해 노력하자~</h1>

{% endblock body %}